/*
 * LEDMatrixSPIMaster.h
 *
 * Created: 11/8/2018 10:01:35 AM
 *  Author: raghu
 */ 


#ifndef LEDMATRIXSPIMASTER_H_
#define LEDMATRIXSPIMASTER_H_

#define CONF_MASTER_MUX_SETTING SPI_SIGNAL_MUX_SETTING_A
#define CONF_MASTER_PINMUX_PAD0 PINMUX_PA30C_SERCOM1_PAD0
#define CONF_MASTER_PINMUX_PAD1 PINMUX_PA31C_SERCOM1_PAD1
#define CONF_MASTER_PINMUX_PAD2 PINMUX_UNUSED
#define CONF_MASTER_PINMUX_PAD3 PINMUX_UNUSED
#define CONF_MASTER_SPI_MODULE  SERCOM1

#define SPIBAUDRATE 2500000

void SPIMasterInit();
void startTransferDMA();
void setUpDMAData(uint8_t* receiveData);
#endif /* LEDMATRIXSPIMASTER_H_ */